# .github/workflows/lint.yml
name: Ansible Lint

# This workflow runs on every push and pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Run ansible-lint
    runs-on: ubuntu-latest

    steps:
      # This step checks out a copy of your repository code
      - name: Check out the repository
        uses: actions/checkout@v4

      # This step runs the ansible-lint action
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6
